2020-01-16 14:25:55,803 ERROR: Exception on /admin/patient-registration/ [GET] [in /Users/AlexYang/anaconda3/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/AlexYang/anaconda3/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/AlexYang/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/AlexYang/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/AlexYang/anaconda3/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/AlexYang/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/AlexYang/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/AlexYang/anaconda3/lib/python3.6/site-packages/flask_admin/base.py", line 69, in inner
    return self._run_view(f, *args, **kwargs)
  File "/Users/AlexYang/anaconda3/lib/python3.6/site-packages/flask_admin/base.py", line 368, in _run_view
    return fn(self, *args, **kwargs)
TypeError: index() takes 0 positional arguments but 1 was given
2020-01-16 14:26:01,376 ERROR: Exception on /admin/patient-registration/ [GET] [in /Users/AlexYang/anaconda3/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/Users/AlexYang/anaconda3/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/AlexYang/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/AlexYang/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/AlexYang/anaconda3/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/AlexYang/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/AlexYang/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/AlexYang/anaconda3/lib/python3.6/site-packages/flask_admin/base.py", line 69, in inner
    return self._run_view(f, *args, **kwargs)
  File "/Users/AlexYang/anaconda3/lib/python3.6/site-packages/flask_admin/base.py", line 368, in _run_view
    return fn(self, *args, **kwargs)
TypeError: index() takes 0 positional arguments but 1 was given
2020-01-17 13:41:53,283 INFO: Mt Rainier startup [in /Users/AlexYang/mt.rainier-form/app/__init__.py:56]
2020-01-17 14:10:21,373 INFO: Mt Rainier startup [in /Users/AlexYang/mt.rainier-form/app/__init__.py:56]
2020-02-02 15:20:51,966 INFO: Mt Rainier startup [in /Users/AlexYang/mt.rainier-form/app/__init__.py:56]
